# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/squirrel_banking_notebooks',
                'doc_host': 'https://erozon.github.io',
                'git_url': 'https://github.com/erozon/squirrel_banking_notebooks',
                'lib_path': 'squirrel_banking_notebooks'},
  'syms': { 'squirrel_banking_notebooks.core': { 'squirrel_banking_notebooks.core.foo': ( 'core.html#foo',
                                                                                          'squirrel_banking_notebooks/core.py')}}}
